version: 1
disable_existing_loggers: False
filters:
  correlation_id:
    "()": asgi_correlation_id.CorrelationIdFilter
    uuid_length: 16
    default_value: '-'
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format:  '[%(asctime)s.%(msecs)03dZ] [%(correlation_id)s] %(levelprefix)s %(message)s'
    use_colors: True
  access:
    "()": uvicorn.logging.AccessFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] [%(correlation_id)s] %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    filters: 
      - correlation_id
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    filters: 
      - correlation_id
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no